jbkuczma/moose

goodbye.py

for #8 woohoo

---

new_file1.py

this is my file for activity 3

---

Moose_lecture.py

#7 Used to print MOOSE

---

www/css/create_room.css
www/css/login.css

pull request for #25. the font family for the login page and create/join room page will match the font family of the room page

for #25 changed font family to match bootstrap

---

package-lock.json
package.json
server/auth.js
server/hash.js
server/server.js
www/css/login.css
www/html/login.html
www/js/login.js

pull request for #14. with this a user can create an account and login

for #14 add authentication and account creation

---

create_clean_db.sh

for #6. shell script to create a fresh moose database

for #6 shell script to create a fresh moose database

---

server/auth.js

there was a lbug with the regex for validation

for #14 fix for login bug

---

.gitignore
.idea/vcs.xml
server/server.js
www/html/create_room.html

#15 create room name associated with a join code that re-routes to main room and data gets stored into  database

Backend on create room #15

---

www/css/create_room.css

backend on create room, fixing CSS bugs for submit buttons

---

server/server.js
www/html/create_room.html

#16 users can now join using a valid room code

Join room code

---

www/css/create_room.css
www/html/create_room.html

issue #37 to fix bug in error for room number text generated incorrectly.

fixing bug issue #37

---

server/server.js

fixed duplicate room code bug #32

Bug fix issue#32

---

server/server.js

continuation for #32. we were missing a closing bracket

missing closing bracket #32

---

.gitignore
package-lock.json
package.json
server/server.js
www/html/the_room.html

Piece of #18 issue is not fully resolved, backend is getting correct results, need to associate with frontend

YouTube search #18

---

package-lock.json
server/server.js

update the current room for a user is in #36

Update current room #36

---

create_clean_db.sh
package-lock.json
package.json
server/server.js
www/css/the_room.css
www/html_templates/the_room.handlebars
www/js/youtube.js

for #18 and #19. this should be the last feature merge for our mvp.

Frontend search #18 #19

---

README.md
package-lock.json
package.json
server/example.keys.js

@deankostorowski @Rmiller1673 please review the updated README and let me know if anything needs to be changed before I create our MVP release for #35

for #35 - update our readme for the MVP release

---

server/server.js

for #54. if a user is not logged in, they should not be able to try and create, join, or enter a room

for #54 ensure user is logged in

---

server/server.js
www/css/the_room.css
www/html_templates/the_room.handlebars
www/js/room.js

#62 a few fixes for the queue and an added overlay after adding a song to the queue

#62 Queue fixes

---

server/auth.js
server/server.js
www/html/create_room.html
www/html/login.html
www/js/login.js

bug chasing to catch errors with user inputs, an extension of issue #53

Errors handling inputs #53

---

server/server.js

should be working now, had issue with creating a room error not handled #53

Error handling for inputs #53

---

README.md
licenses/background_images_licenses.txt
licenses/landy_license.txt
www/html/index.html

licenses and wording #58

---

server/server.js

Please find that the bug for Youtube Channels breaking a room is now taken care of #72

Youtube channel bug

---

create_clean_db.sh
package-lock.json
package.json
server/server.js
www/html_templates/the_room.handlebars
www/js/room.js
www/js/youtube.js

#74 our add on feature. guests should know what songs have already been played so the same song is not repeated.

Add On - show guests previously played songs for a room #74

---

www/css/the_room.css
www/html_templates/the_room.handlebars

#78  A helpful Beta tester pointed out that it would be nice to have a message as to why there was an overlay being produced after a song was to the queue. Please find that these changes make that happen.

Overlay resaon message

---

server/server.js
www/js/room.js

release touchups #76

---

www/css/the_room.css

Width for search results updated to 100%
